sudo: required
services:
    - docker
    
before_install:
    - docker build -t gampakaushik/docker -f Dockerfile.dev .
    
script:
    - docker run -e CI=true gampakaushik/docker npm run test 
